[workspace]
members = ["crates/fleximl-models"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Elesdes"]
license = "MIT"

[workspace.dependencies]
ndarray = "0.15.6"
rand = "0.8.5"
approx = "0.5.1"

[profile.dev]
debug = 0
opt-level = 2
lto = true
