name: FlexiML Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_tests:
    name: FlexiML - Rust Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Run Rust Tests
        run: cargo test --verbose

  python_tests:
    name: FlexiML - Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install initial requirements
        run: pip install "maturin>=1.4,<=2.0" pytest==8.3.2
      - name: Build and Install FlexiML
        run: |
          maturin build
          pip install target/wheels/*.whl
      - name: Run Python Tests
        run: pytest pytests

  notify_ci_status:
    name: Notify CI Status
    needs: [rust_tests, python_tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check job status
        id: check
        run: |
          if [ "${{ needs.rust_tests.result }}" == "success" ] && [ "${{ needs.python_tests.result }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          elif [ "${{ needs.rust_tests.result }}" == "cancelled" ] || [ "${{ needs.python_tests.result }}" == "cancelled" ]; then
            echo "status=cancelled" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: steps.check.outputs.status == 'success'
        with:
          severity: info
          details: All tests succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: steps.check.outputs.status == 'failure'
        with:
          severity: error
          details: One or more tests failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: steps.check.outputs.status == 'cancelled'
        with:
          severity: warn
          details: Tests were cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
