name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: FlexiML - latest
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
        - uses: actions/checkout@v4
        - run: rustup update stable && rustup default stable
        - run: cargo build --verbose
        - run: cargo test --verbose
