name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: FlexiML - latest
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
        - uses: actions/checkout@v4
        - run: rustup update stable && rustup default stable
        - run: cargo build --verbose
        - run: cargo test --verbose
    notify_ci_status:
        runs-on: ubuntu-latest
        steps:
          - name: Test Success
            uses: rjstone/discord-webhook-notify@v1
            if: success()
            with:
              severity: info
              details: Test Succeeded!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          - name: Test Failure
            uses: rjstone/discord-webhook-notify@v1
            if: failure()
            with:
              severity: error
              details: Test Failed!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          - name: Test Cancelled
            uses: rjstone/discord-webhook-notify@v1
            if: cancelled()
            with:
              severity: warn
              details: Test Cancelled!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}