on:
  workflow_call:
    inputs:
      crate:
        required: true
        type: string
    secrets:
      CRATES_IO_API_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust & Dependencies
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo run -p xtask publish ${{ inputs.crate }}
        env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
