name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    if: needs.test.outputs.tests_passed == 'true'
    strategy:
      matrix:
        crate:
          - fleximl-models
    uses: ./.github/workflows/publish-template.yml
    with:
      crate: ${{ matrix.crate }}
    secrets: inherit
