name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    publish-fleximl-models:
        uses: Elesdes/FlexiML/.github/workflows/publish-template.yml@master
        with:
            crate: fleximl-models
        secrets: inherit
