name: Test

on:
  push:
    branches:
      - master
  workflow_call:
    outputs:
      tests_passed:
        description: "Indicates if tests passed"
        value: ${{ jobs.tests_and_coverage.outputs.tests_passed }}

env:
  CARGO_TERM_COLOR: always

jobs:
  tests_and_coverage:
    name: Tests and Coverage
    runs-on: ubuntu-latest
    outputs:
      tests_passed: ${{ steps.test_status.outputs.tests_passed }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Tests
        id: run_tests
        run: cargo test --verbose
        continue-on-error: true

      - name: Set test status
        id: test_status
        if: always()
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            echo "tests_passed=true" >> $GITHUB_OUTPUT
          else
            echo "tests_passed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Coverage
        if: steps.run_tests.outcome == 'success'
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out Xml
