name: Test

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  tests_and_coverage:
    name: Tests and Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Tests
        run: cargo test --verbose

      - name: Run Coverage
        run: cargo tarpaulin --verbose --workspace --timeout 120 --out Xml
